apiVersion: v1
kind: Namespace
metadata:
  name: sandbox

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: sandbox
  labels:
    app: test-a
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 3600"]

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: sandbox
  labels:
    app: test-b
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
