apiVersion: v1
kind: Pod
metadata:
  name: cpu-hog
  namespace: attack
  labels:
    app: cpu-hog
spec:
  containers:
  - name: busy
    image: python:3.11-slim
    resources:
      limits:
        cpu: "0.5"
    command: ["python","-c","while True: pass"]
